import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";
import Script from "next/script";
import { Providers } from "@/components/providers";
import { Header } from "@/components/header";
import dayjs from "dayjs";
import timezone from "dayjs/plugin/timezone";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "のりまっし泉丘",
  description: "Generated by create next app",
};

dayjs.extend(timezone);
dayjs.tz.setDefault("Asia/Tokyo");

// const gtag = "G-Y9T104VC35";
const gtag = "";

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="ja">
      {/* <Script
        strategy="afterInteractive"
        src={`https://www.googletagmanager.com/gtag/js?id=${gtag}`}
      />
      <Script
        id="gtag-init"
        strategy="afterInteractive"
        dangerouslySetInnerHTML={{
          __html: `
           window.dataLayer = window.dataLayer || [];
           function gtag(){dataLayer.push(arguments);}
           gtag('js', new Date());
 
           gtag('config', '${gtag}');
           `,
        }}
      /> */}
      <body className={inter.className}>
        <Header />
        <Providers>{children}</Providers>
      </body>
    </html>
  );
}
